### ISSUE TITLE
nodes are hang up

### ISSUE THREAD

**Issue by bitkevin** [bitcoinfibre/bitcoinfibre#2] opened 2016-08-15 02:30 UTC
I have 6 fibre nodes and they all have the same problem. One cpu 100% and block height stoped.
- Host OS: `Ubuntu 14.04.4 LTS`
- Docker: `version 1.12.0, build 8eab29e`
  - Iamge OS: `Ubuntu 16.04 LTS`

---

`strace -p 21822`

```
Process 21822 attached
restart_syscall(<... resuming interrupted call ...>) = -1 ETIMEDOUT (Connection timed out)
futex(0x7f3b373a6d28, FUTEX_WAKE_PRIVATE, 1) = 0
clock_gettime(CLOCK_REALTIME, {1471227925, 273404969}) = 0
futex(0x7f3b373a6d54, FUTEX_WAIT_BITSET_PRIVATE|FUTEX_CLOCK_REALTIME, 4335417, {1471227925, 473404969}, ffffffff) = -1 ETIMEDOUT (Connection timed out)
futex(0x7f3b373a6d28, FUTEX_WAKE_PRIVATE, 1) = 0
clock_gettime(CLOCK_REALTIME, {1471227925, 473767212}) = 0
futex(0x7f3b373a6d54, FUTEX_WAIT_BITSET_PRIVATE|FUTEX_CLOCK_REALTIME, 4335419, {1471227925, 673767212}, ffffffff) = -1 ETIMEDOUT (Connection timed out)
futex(0x7f3b373a6d28, FUTEX_WAKE_PRIVATE, 1) = 0
clock_gettime(CLOCK_REALTIME, {1471227925, 674092490}) = 0
futex(0x7f3b373a6d54, FUTEX_WAIT_BITSET_PRIVATE|FUTEX_CLOCK_REALTIME, 4335421, {1471227925, 874092490}, ffffffff) = -1 ETIMEDOUT (Connection timed out)
futex(0x7f3b373a6d28, FUTEX_WAKE_PRIVATE, 1) = 0
clock_gettime(CLOCK_REALTIME, {1471227925, 874423387}) = 0
futex(0x7f3b373a6d54, FUTEX_WAIT_BITSET_PRIVATE|FUTEX_CLOCK_REALTIME, 4335423, {1471227926, 74423387}, ffffffff) = -1 ETIMEDOUT (Connection timed out)
futex(0x7f3b373a6d28, FUTEX_WAKE_PRIVATE, 1) = 0
clock_gettime(CLOCK_REALTIME, {1471227926, 74771864}) = 0
futex(0x7f3b373a6d54, FUTEX_WAIT_BITSET_PRIVATE|FUTEX_CLOCK_REALTIME, 4335425, {1471227926, 274771864}, ffffffff) = -1 ETIMEDOUT (Connection timed out)
futex(0x7f3b373a6d28, FUTEX_WAKE_PRIVATE, 1) = 0
clock_gettime(CLOCK_REALTIME, {1471227926, 275112271}) = 0
futex(0x7f3b373a6d54, FUTEX_WAIT_BITSET_PRIVATE|FUTEX_CLOCK_REALTIME, 4335427, {1471227926, 475112271}, ffffffff) = -1 ETIMEDOUT (Connection timed out)
futex(0x7f3b373a6d28, FUTEX_WAKE_PRIVATE, 1) = 0
clock_gettime(CLOCK_REALTIME, {1471227926, 475514330}) = 0
futex(0x7f3b373a6d54, FUTEX_WAIT_BITSET_PRIVATE|FUTEX_CLOCK_REALTIME, 4335429, {1471227926, 675514330}, ffffffff) = -1 ETIMEDOUT (Connection timed out)
futex(0x7f3b373a6d28, FUTEX_WAKE_PRIVATE, 1) = 0
clock_gettime(CLOCK_REALTIME, {1471227926, 675934973}) = 0
futex(0x7f3b373a6d54, FUTEX_WAIT_BITSET_PRIVATE|FUTEX_CLOCK_REALTIME, 4335431, {1471227926, 875934973}, ffffffff^CProcess 21822 detached
 <detached ...>
```

latest debug.log: 

```
2016-08-14 23:56:57 connect() to 222.58.42.148:8333 failed after select(): Connection refused (111)
2016-08-15 00:00:21 socket sending timeout: 1201s
2016-08-15 00:00:24 socket sending timeout: 1201s
2016-08-15 00:00:28 connect() to [2a01:4f8:100:1190::2]:8333 failed: Network is unreachable (101)
2016-08-15 00:00:34 connect() to 66.75.124.172:8333 failed after select(): Connection refused (111)
2016-08-15 00:01:18 connect() to [2001:0:5ef5:79fd:3ceb:376b:faf3:e639]:8333 failed: Network is unreachable (101)
2016-08-15 00:04:40 socket sending timeout: 1201s
2016-08-15 00:04:40 connect() to 181.95.132.73:8333 failed after select(): Connection refused (111)
2016-08-15 00:11:54 socket sending timeout: 1201s
2016-08-15 00:16:58 socket sending timeout: 1201s
2016-08-15 00:20:22 socket sending timeout: 1201s
2016-08-15 00:21:25 socket sending timeout: 1201s
2016-08-15 00:34:28 connect() to 31.10.91.118:8333 failed after select(): Connection refused (111)
2016-08-15 00:34:34 connect() to 107.191.36.21:8333 failed after select(): Connection refused (111)
2016-08-15 00:34:35 connect() to [2001:0:5ef5:79fb:70:381e:b995:16f0]:8333 failed: Network is unreachable (101)
2016-08-15 00:36:59 socket sending timeout: 1201s
2016-08-15 00:40:28 socket sending timeout: 1201s
2016-08-15 00:41:13 connect() to 99.254.122.213:8333 failed after select(): No route to host (113)
2016-08-15 00:41:19 connect() to [2a01:4f8:d16:9384::2]:8333 failed: Network is unreachable (101)
2016-08-15 00:41:31 connect() to 46.59.157.159:8333 failed after select(): No route to host (113)
2016-08-15 00:44:42 socket sending timeout: 1201s
2016-08-15 00:51:55 connect() to 222.58.42.148:8333 failed after select(): Connection refused (111)
2016-08-15 01:01:26 socket sending timeout: 1201s
2016-08-15 01:01:36 connect() to 89.143.118.8:8333 failed after select(): No route to host (113)
2016-08-15 01:04:48 socket sending timeout: 1201s
2016-08-15 01:11:57 connect() to 81.230.10.247:8333 failed after select(): Connection refused (111)
2016-08-15 01:11:58 connect() to 110.248.187.157:8333 failed after select(): Connection refused (111)
2016-08-15 01:14:48 connect() to 178.162.205.21:8333 failed after select(): Connection refused (111)
2016-08-15 01:17:00 socket sending timeout: 1201s
2016-08-15 01:20:30 socket sending timeout: 1201s
2016-08-15 01:21:49 socket sending timeout: 1201s
2016-08-15 01:21:50 socket sending timeout: 1201s
2016-08-15 01:22:01 connect() to 92.193.81.16:8333 failed after select(): No route to host (113)
2016-08-15 01:32:05 connect() to [2001:0:9d38:6abd:2c3a:2af5:8f56:99d0]:8333 failed: Network is unreachable (101)
2016-08-15 01:34:49 socket sending timeout: 1201s
2016-08-15 01:40:31 connect() to 85.93.205.5:8333 failed after select(): No route to host (113)
2016-08-15 01:42:08 socket sending timeout: 1201s
2016-08-15 01:42:20 connect() to [2001:a61:301b:2f01:bbc1:2200:a3e3:a528]:8333 failed: Network is unreachable (101)
2016-08-15 01:44:49 socket sending timeout: 1201s
2016-08-15 01:44:49 connect() to [2a01:4f8:140:6333::2]:8333 failed: Network is unreachable (101)
2016-08-15 01:44:50 connect() to 104.238.169.111:8333 failed after select(): Connection refused (111)
2016-08-15 01:52:09 connect() to 188.192.186.47:8333 failed after select(): No route to host (113)
2016-08-15 01:54:55 connect() to 116.237.210.163:8333 failed after select(): Connection refused (111)
2016-08-15 01:57:01 socket sending timeout: 1201s
2016-08-15 01:57:01 connect() to 201.242.58.211:8333 failed after select(): Connection refused (111)
2016-08-15 02:02:17 connect() to 88.122.117.41:8333 failed after select(): No route to host (113)
2016-08-15 02:12:16 socket sending timeout: 1201s
2016-08-15 02:12:16 connect() to [2001:0:9d38:6abd:38fd:28f6:3d19:6096]:8333 failed: Network is unreachable (101)
2016-08-15 02:15:07 socket sending timeout: 1201s
2016-08-15 02:20:56 socket sending timeout: 1201s
2016-08-15 02:22:25 socket sending timeout: 1201s
2016-08-15 02:22:35 connect() to [2001:0:9d38:6abd:14:2c82:9c14:615f]:8333 failed: Network is unreachable (101)
```

**Comment by bitkevin** [comment] 2016-08-15 02:31
`Dockerfile`

```
RUN apt-get update
RUN apt-get install -y build-essential libtool autotools-dev automake pkg-config libssl-dev libevent-dev bsdmainutils yasm
RUN apt-get install -y libboost-all-dev libzmq3-dev git

# build bitcoind
RUN mkdir ~/source
RUN cd ~/source \
  && git clone https://github.com/bitcoinfibre/bitcoinfibre.git \
  && cd bitcoinfibre \
  && ./autogen.sh \
  && ./configure --disable-wallet \
  && make -j4 && make install
```

**Comment by TheBlueMatt** [comment] 2016-08-16 01:03
Have you tried the version at https://github.com/TheBlueMatt/bitcoin/tree/udp-wip? I just pushed that to master here and tagged it -b2 since its been stable for me. Any chance, when you restart bitcoind on that box, you could run it in gdb and run "thread apply all bt" when it freezes to get a backtrace of all the locked threads...the above logs dont really help in debugging a deadlock, sadly.

**Comment by bitkevin** [comment] 2016-08-16 02:37
Yesterday  I have  checking out `udp-wip` and  it's works fine so far.

```
RUN cd ~/source \
  && git clone https://github.com/TheBlueMatt/bitcoin.git \
  && cd bitcoin \
  && git checkout origin/udp-wip \
  && ./autogen.sh \
  && ./configure --disable-wallet \
  && make -j2 && make install
```

---

All nodes in Beijing doesn't work (they connect to HongKong). I use `nc -vuz <host> <port>` to check udp package and turned out success but `debug.log` always show `UDP: Peer <host>:<port> timed out`.

**Comment by TheBlueMatt** [comment] 2016-08-16 18:22
Does -z work for UDP on nc? I'd think it would just return success without actually generating any network traffic.

As for Beijing not routing, that is a shame, I'm assuming GFW is dropping it. I had no problem connecting to my own node on Aliyun, though didn't test it extensively. You might try using a different hosting provider in HKG/BJS and additionally adding a hosting provider in Tokyo, which generally will give you lower latency from BJS to the US as NTT has China Unicom/Telecom peering there.

**Comment by TheBlueMatt** [comment] 2016-12-21 07:10
Because a lot of code has been rewritten since August and I couldn't ever reproduce I'm gonna go ahead and close this.

**Closed as completed by TheBlueMatt** 2016-12-21 07:10 UTC
